### ISSUE TITLE
[DDA-124] Refactoring

### ISSUE THREAD

**Issue by choincnp** [DDAL-GGAK/DDAL-GGAK-BE#228]
sonarlint로 검증 후 리팩터링 적용

<sub>From [SyncLinear.com](https://synclinear.com) | [DDA-124](https://linear.app/ddal-ggak/issue/DDA-124/refactoring)</sub>

**Comment by aihtnyc-h** [comment]
화이팅!!

**Comment by aihtnyc-h** [comment]
할 수 있다!!
